version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.2
    steps:
      - checkout
      - run: python Implicit_wait.py

  test:
    docker:
      - image: cimg/python:3.2
    steps:
      - checkout
      - run: python Implicit_wait.py

workflows:
  build_now:
    jobs:
      - build
      - test
