version: 2.1

executors:
  selenium:
    docker:
      - image: circleci/python:3.8-browsers
    working_directory: ~/repo
    
jobs:
  test_Explicit_Wait:
    executor: selenium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
   

      - run:
          command: python Files/explicit_wait.py

  test_Fluent_wait:
    executor: selenium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
   

      - run:
          command: python Files/Fluent_wait.py
workflows:
  version: 2
  sequence_of_execution:
    jobs:
      - test_Explicit_Wait
      - test_Fluent_wait
